### ISSUE TITLE
手势侧滑POP的时候，有个小问题

### ISSUE THREAD

**Issue by huangxinyu1213** [HelloYeah/HYNavBarHidden#1]

**Comment by HelloYeah** [comment]
这的确是个很严重的BUG.不好解决.

**Comment by HelloYeah** [comment]
可能要重写底层的侧滑手势动画效果..暂时没想到更好的方案,你有什么思路吗

**Comment by huangxinyu1213** [comment]
额，我也不知道😳😳😳

发自 网易邮箱大师
在2016年04月10日 16:04，HelloYeah 写道:

可能要重写底层的侧滑手势动画效果..暂时没想到更好的方案,你有什么思路吗

**Comment by Dengfulei** [comment]
偶尔POP的时候，下个界面navbar是白色的

**Comment by HelloYeah** [comment]
当设置了navbar背景图片时,手势侧滑,这个分类会有BUG.原因是在viewWillApper中重新设置了导航条的背景图片.暂时不知道怎么解决. @Dengfulei

**Comment by linminjing666** [comment]
楼主，[self doDeviceVersion] 这个在xcode8下，返回结果一直未0，让我找了好久，offset以为为一个定值，屏幕的高。（iPhone 7 iPhone7p模拟器测试）
