### ISSUE TITLE
message sent to deallocated instance

### ISSUE THREAD

**Issue by zoey0820ivy** [HelloYeah/HYNavBarHidden#10]
您好，我想用你这个接口写个效果，可是我只要导入你的类到我的项目 只要导航栏返回的时候就会报message sent to deallocated instance 错误，不清楚什么情况！

**Comment by HelloYeah** [comment]
你用最新代码试一下。

**Comment by zoey0820ivy** [comment]
谢谢@HelloYeah 我自己调好了 一开始就是用的最新代码, 解决方案是把你的代码用MRC处理就好了 本身我的项目是用ARC处理的。

**Comment by HelloYeah** [comment]
嗯。。
