### ISSUE TITLE
继承的枚举冲突

### ISSUE THREAD

**Issue by orangutans** [HelloYeah/HYNavBarHidden#11]
在 UIViewController+NavBarHidden 的里面，定义的枚举，还有在控制器里面定义的枚举，这二个枚举是冲突的，为什么你项目中没有冲突？？？还有为什么二个地方都要写？？扩展类里面写了，在继承类里面怎么还写呢？？？能否解释下？谢谢楼主！！

**Comment by orangutans** [comment]
![image](https://cloud.githubusercontent.com/assets/8220011/21474790/e5ce438c-cb5e-11e6-9796-d7c67285a0ac.png)

**Comment by HelloYeah** [comment]
你控制器继承了HYViewController，就不要导入分类了。HYViewController.h 和UIViewController+NavBarHidden.h  两个头文件不同时导入。两种实现方案，你用的时候直接选择其中一种就行了。
