### ISSUE TITLE
self.navigationItem.title

### ISSUE THREAD

**Issue by zuocai1993** [HelloYeah/HYNavBarHidden#3]
self.navigationItem.title 这样设置的导航标题 如何去隐藏？

**Comment by HelloYeah** [comment]
这样设置的标题,没有实现跟着隐藏.可以设置self.navigationItem.titleView

**Comment by Pikdays** [comment]
@HelloYeah 同问

**Comment by HelloYeah** [comment]
这样的通过runtime去隐藏.
