### ISSUE TITLE
不能跳转。

### ISSUE THREAD

**Issue by steve-four** [HelloYeah/HYNavBarHidden#5]
当在一个界面引用了此代码，当再push时，直接崩掉，Bug一堆。

**Comment by HelloYeah** [comment]
有时间会把它改造成自定义的导航条,导航条共用一直是比较麻烦的事.

**Comment by steve-four** [comment]
这个其实没你想的那么复杂，既然你在进入控制器的时候设置了空的图片，为什么不在他消失的时候再设置回来呢？你这只能当做一个Demo，不能用到项目中。

**Comment by HelloYeah** [comment]
你说的是我以前 的方案,但会影响手势侧滑.

**Comment by HelloYeah** [comment]
在手势侧滑的时候,导航条的样式和侧滑效果会有问题

**Comment by HelloYeah** [comment]
你可以自己试试...

**Comment by steve-four** [comment]
你把这写，消失和显现的方法写到willapper和disapper中是可以的，但是别用全屏侧滑是不会有问题的，侧滑也是显示和消失。怎么会有问题呢？我项目中就是这样做的。

**Comment by HelloYeah** [comment]
两个控制器共用一个导航条,当两个控制器导航条样式不一样的时候,侧滑返回,滑在中间的时候,怎么显示,显示效果是怎么样..

**Comment by steve-four** [comment]
当他滑到中间的时候，就显示出导航。

**Comment by HelloYeah** [comment]
我第一次用的就是这个方案,简书链接.我一直没有更好的方案,在不影响系统侧滑下实现效果.现在的demo是后面改成这样的.简化了接口.去掉了willapper和disapper两个方法.如果禁用手势侧滑的话,那就没什么问题,但我不想那样做.这个demo仅供学习吧.用到项目中,还是有问题.http://www.jianshu.com/p/ac237ebcd4fb
