### ISSUE TITLE
storyboard添加有问题

### ISSUE THREAD

**Issue by honeycao** [HelloYeah/HYNavBarHidden#6]
我看到demo中有一个用storyboard添加的可以，但是在自己新建一个并在storyboard创建left、title、right的时候就不能隐藏了，只是背景隐藏，后来改为代码创建，就又可以了，没找到原因，求解。。。

**Comment by HelloYeah** [comment]
这要看，你添加的是什么控件，源码里取的是tabBarItem的customView，有的这样取是拿不到的。
